# This file was generated by GoReleaser. DO NOT EDIT.
cask "actup" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "1ebcc8e89918a2f7f372dc32d3da0d7b8a1b02ec9ca21eb742c177e8842b8790"
      url "https://github.com/jcouture/actup/releases/download/v#{version}/actup_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d5f9cf805fe2ba62e7b24e42d03f6a525f18bc5144e97c6a8a9ed8acaa12c42e"
      url "https://github.com/jcouture/actup/releases/download/v#{version}/actup_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d876cdc5ef0f81e592e9a01feb52cd19a4fd609bee1fc5faca6429c9d1154ae3"
      url "https://github.com/jcouture/actup/releases/download/v#{version}/actup_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ff3f5b1c8121c8e128b8864ce99c7bbf369f0edc16a658c3a66f0defb78e8839"
      url "https://github.com/jcouture/actup/releases/download/v#{version}/actup_#{version}_linux_amd64.tar.gz"
    end
  end

  name "actup"
  desc "Pin GitHub Actions to immutable commit SHAs"
  homepage "https://github.com/jcouture/actup"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "actup"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/actup"]
    end
  end

  # No zap stanza required
end
