# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghostscan" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "8c7aec7182465abac38b07e536c62c6f885206ca516b37ba023e9e467fb2110e"
      url "https://github.com/jcouture/ghostscan/releases/download/v#{version}/ghostscan_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3d6e8a8c1deab3fff9e02b82df2375cb1d76ef40aff77a17e9c1c3f2aa5dd8ef"
      url "https://github.com/jcouture/ghostscan/releases/download/v#{version}/ghostscan_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9ec993ea6861450ccb362e6abea6ccbc2c5ff056d0d9354bbd918e9386154b25"
      url "https://github.com/jcouture/ghostscan/releases/download/v#{version}/ghostscan_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "accfaa9127b4cdab9e5b72b7754394099b60f23e5c2d3df53201ff6df312d7c9"
      url "https://github.com/jcouture/ghostscan/releases/download/v#{version}/ghostscan_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ghostscan"
  desc "Static Unicode security scanner for developers and CI teams"
  homepage "https://github.com/jcouture/ghostscan"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghostscan"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghostscan"]
    end
  end

  # No zap stanza required

end
