# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghostscan" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "2f9d3093bd94085d65d082d3ea2ea7b805d8a60515695599a3c759bc26748cdb"
      url "https://github.com/jcouture/ghostscan/releases/download/v#{version}/ghostscan_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cca17b879c727a768bb9b4856e5a71ae2199f1ade52bd4288d8cee97fd8ba196"
      url "https://github.com/jcouture/ghostscan/releases/download/v#{version}/ghostscan_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5ba4dfe3dc9d7ee9b4bb206e999578ed576854944f05313e05c852522c71347d"
      url "https://github.com/jcouture/ghostscan/releases/download/v#{version}/ghostscan_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a3de4d4b5eaef6b46b7d24d652c5830a3246403fa65a7308c584257f616a6e48"
      url "https://github.com/jcouture/ghostscan/releases/download/v#{version}/ghostscan_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ghostscan"
  desc "Static Unicode security scanner for developers and CI teams"
  homepage "https://github.com/jcouture/ghostscan"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghostscan"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghostscan"]
    end
  end

  # No zap stanza required

end
