# This file was generated by GoReleaser. DO NOT EDIT.
cask "nv" do
  version "3.0.0"

  on_macos do
    on_intel do
      sha256 "f3dfdcf5c6fa8174163cfe7fa116d7597e66c0444fc0fe262212c3bc8f72630a"
      url "https://github.com/jcouture/nv/releases/download/#{version}/nv_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "db3253cc07a9db191c0a3e96d16b444da82a426eb2e152ee9a55503dde6d0753"
      url "https://github.com/jcouture/nv/releases/download/#{version}/nv_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ee7ba458f1962715400eadb1c6d33d6c5c748ade142674e5007942384b75b789"
      url "https://github.com/jcouture/nv/releases/download/#{version}/nv_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c83b5581b11b46e8912f9dae6004703ce7f5e3015867225a9d64f9d656bb2fe0"
      url "https://github.com/jcouture/nv/releases/download/#{version}/nv_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nv"
  desc "Lightweight utility to load context specific environment variables"
  homepage "https://github.com/jcouture/nv"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nv"]
    end
  end

  # No zap stanza required

end
