# This file was generated by GoReleaser. DO NOT EDIT.
cask "nv" do
  version "3.0.1"

  on_macos do
    on_intel do
      sha256 "b1db43927bbd67712c19d30fe41c7372680efe652a03a7ebcdd452a450420efc"
      url "https://github.com/jcouture/nv/releases/download/#{version}/nv_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d2804f7cdeee8b6a2452caa482ff90dfedd1b0f84f23a0a0058cd30cecaf6899"
      url "https://github.com/jcouture/nv/releases/download/#{version}/nv_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4279085fac61db74c95691a931d9266ceeac7f58c8d82ea07a1eea920a4a329b"
      url "https://github.com/jcouture/nv/releases/download/#{version}/nv_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5ac7469e349c9b27fd945f76164664d63f6800891fd62e2acb39504b12ccad3a"
      url "https://github.com/jcouture/nv/releases/download/#{version}/nv_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nv"
  desc "Lightweight utility to load context specific environment variables"
  homepage "https://github.com/jcouture/nv"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nv"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nv"]
    end
  end

  # No zap stanza required

end
